# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lw < Formula
  desc "LightWave CLI - Task management and platform operations"
  homepage "https://github.com/lightwave-media/lightwave-cli"
  version "2.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v2.10.0/lightwave-cli_2.10.0_darwin_amd64.tar.gz"
      sha256 "ec129e66d2a95b1f51e8b6e3941edb008d3e73b521a569d1d98c1db2267e9b3a"

      define_method(:install) do
        bin.install "lw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v2.10.0/lightwave-cli_2.10.0_darwin_arm64.tar.gz"
      sha256 "7eef8d92b9e73879ba5e7278b107d9066ee457c79f13bfebcc48b575e9f52f05"

      define_method(:install) do
        bin.install "lw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v2.10.0/lightwave-cli_2.10.0_linux_amd64.tar.gz"
      sha256 "8a080d30b96f0b3354fbba19f629bc7a566c51f05fa02ce1fc490a3333e80dc0"
      define_method(:install) do
        bin.install "lw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v2.10.0/lightwave-cli_2.10.0_linux_arm64.tar.gz"
      sha256 "27c14e91f3ee347cacdd94df0e2d7dfcce1c5383a16a92517481bc1e54c490cc"
      define_method(:install) do
        bin.install "lw"
      end
    end
  end

  test do
    assert_match "lw version", shell_output("#{bin}/lw version")
  end
end
