# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lw < Formula
  desc "LightWave CLI - Task management and platform operations"
  homepage "https://github.com/lightwave-media/lightwave-cli"
  version "3.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v3.2.0/lightwave-cli_3.2.0_darwin_amd64.tar.gz"
      sha256 "d041ff348036179c99066596690c15992b53413302e7d2bfc00e25ae1c6f5334"

      define_method(:install) do
        bin.install "lw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v3.2.0/lightwave-cli_3.2.0_darwin_arm64.tar.gz"
      sha256 "543d60cbfe903fbd04a81aa7c9ba942114169b4d1bdd21755ab2db5a1f80ae0d"

      define_method(:install) do
        bin.install "lw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v3.2.0/lightwave-cli_3.2.0_linux_amd64.tar.gz"
      sha256 "517a5714018a06f5e0aefdf8fe4d405fb4dd3822ac10765e72a9c6c13d823a02"

      define_method(:install) do
        bin.install "lw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v3.2.0/lightwave-cli_3.2.0_linux_arm64.tar.gz"
      sha256 "c1bcefd28bf57a883cfe82ab5b7ac3d7b763d900cca8d33fad2a93effdc1b97a"

      define_method(:install) do
        bin.install "lw"
      end
    end
  end
end
