# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lw < Formula
  desc "LightWave CLI - Task management and platform operations"
  homepage "https://github.com/lightwave-media/lightwave-cli"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v2.2.0/lightwave-cli_2.2.0_darwin_amd64.tar.gz"
      sha256 "10b4dca556f37b5882494ee6acc3348fcd0c282144ef4eaf9bef30fd3745633e"

      define_method(:install) do
        bin.install "lw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v2.2.0/lightwave-cli_2.2.0_darwin_arm64.tar.gz"
      sha256 "5c3d111eccdc223e8c75f534c23c5450128206b847c306e996a8a4356012c1e3"

      define_method(:install) do
        bin.install "lw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v2.2.0/lightwave-cli_2.2.0_linux_amd64.tar.gz"
      sha256 "2e0cfcad6706b98f719320b6bcb2a7a184d6d58f430ad4d46af687c68ba9e2c8"
      define_method(:install) do
        bin.install "lw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lightwave-media/lightwave-cli/releases/download/v2.2.0/lightwave-cli_2.2.0_linux_arm64.tar.gz"
      sha256 "8e7ad475ff86ad34b6a08a9947601fa2eecf5ae08b3aab16201a090329ce6ee6"
      define_method(:install) do
        bin.install "lw"
      end
    end
  end

  test do
    assert_match "lw version", shell_output("#{bin}/lw version")
  end
end
